# Generated by Django 5.1.2 on 2024-10-20 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=models.CASCADE, to='auth.User')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]